const fetch = require('node-fetch');
const fs = require('fs');

let urls = [
  'https://www.carousell.com.hk/q/整網頁',
  'https://www.carousell.com.hk/q/自動交易程式',
  'https://www.carousell.com.hk/q/python',
  'https://www.carousell.com.hk/q/roblox',
  'https://www.carousell.com.hk/q/網店創業',
  'https://www.carousell.com.hk/q/PowerPoint製作',
  'https://www.carousell.com.hk/q/自動交易',
  'https://www.carousell.com.hk/q/Jupyter',
  'https://www.carousell.com.hk/q/excel%20vba',
  'https://www.carousell.com.hk/q/e-commerce',
  'https://www.carousell.com.hk/q/llama',
  'https://www.carousell.com.hk/q/sba',
  'https://www.carousell.com.hk/q/手機開發',
  'https://www.carousell.com.hk/q/Woocommerce',
  'https://www.carousell.com.hk/q/自訂功能',
  'https://www.carousell.com.hk/q/matlab',
  'https://www.carousell.com.hk/q/開發',
  'https://www.carousell.com.hk/q/ppt',
  'https://www.carousell.com.hk/q/seo',
  'https://www.carousell.com.hk/q/coding',
  'https://www.carousell.com.hk/q/Excel製作',
  'https://www.carousell.com.hk/q/ubuntu',
  'https://www.carousell.com.hk/q/社交媒體推廣',
  'https://www.carousell.com.hk/q/網頁',
  'https://www.carousell.com.hk/q/客製化定製Excel',
  'https://www.carousell.com.hk/q/shell%20script',
  'https://www.carousell.com.hk/q/app',
  'https://www.carousell.com.hk/q/網上創業',
  'https://www.carousell.com.hk/q/programming',
  'https://www.carousell.com.hk/q/deepseek',
  'https://www.carousell.com.hk/q/Wix',
  'https://www.carousell.com.hk/q/網店',
  'https://www.carousell.com.hk/q/表格',
  'https://www.carousell.com.hk/q/linux',
  'https://www.carousell.com.hk/q/代做',
  'https://www.carousell.com.hk/q/it',
  'https://www.carousell.com.hk/q/fedora',
  'https://www.carousell.com.hk/q/PPT製作',
  'https://www.carousell.com.hk/q/openai',
  'https://www.carousell.com.hk/q/FYP代寫代做',
  'https://www.carousell.com.hk/q/javascript',
  'https://www.carousell.com.hk/q/網店平台',
  'https://www.carousell.com.hk/q/gpt',
  'https://www.carousell.com.hk/q/編程',
  'https://www.carousell.com.hk/q/chatgpt',
  'https://www.carousell.com.hk/q/63165608',
  'https://www.carousell.com.hk/q/database',
  'https://www.carousell.com.hk/q/網頁製作',
  'https://www.carousell.com.hk/q/mysql',
  'https://www.carousell.com.hk/q/ai',
  'https://www.carousell.com.hk/q/java',
  'https://www.carousell.com.hk/q/stem',
  'https://www.carousell.com.hk/q/vba',
  'https://www.carousell.com.hk/q/wordpress',
  'https://www.carousell.com.hk/q/App開發',
  'https://www.carousell.com.hk/q/網頁開發',
  'https://www.carousell.com.hk/q/assignment',
  'https://www.carousell.com.hk/q/ict',
  'https://www.carousell.com.hk/q/sql',
  'https://www.carousell.com.hk/q/web',
  'https://www.carousell.com.hk/q/startup',
  'https://www.carousell.com.hk/q/Excel',
  'https://www.carousell.com.hk/q/功課代寫',
  'https://www.carousell.com.hk/q/初創',
  'https://www.carousell.com.hk/q/公司網站',
  'https://www.carousell.com.hk/q/Debug',
  //
  'https://www.carousell.com.hk/q/Cubetto',
  'https://www.carousell.com.hk/q/ScratchJr',
  'https://www.carousell.com.hk/q/Neuron%20Blocks',
  'https://www.carousell.com.hk/q/Jimu%20Robotics',
  'https://www.carousell.com.hk/q/Dash%20&%20Dot%20Robots',
  'https://www.carousell.com.hk/q/Scratch',
  'https://www.carousell.com.hk/q/mBot%20Robotics',
  'https://www.carousell.com.hk/q/Minecraft%20Modding',
  'https://www.carousell.com.hk/q/Roblox%20Coding',
  'https://www.carousell.com.hk/q/AppInventor',
  'https://www.carousell.com.hk/q/Python',
  'https://www.carousell.com.hk/q/Web%20Programming',
  'https://www.carousell.com.hk/q/ITS%20Exam',
  'https://www.carousell.com.hk/q/Data%20Science',
  'https://www.carousell.com.hk/q/Artificial%20Intelligence',
  //
  'https://www.carousell.com.hk/categories/services-1306/?addRecent=true&search=python',
  'https://www.carousell.com.hk/categories/services-1306/?addRecent=true&search=javascript',
  'https://www.carousell.com.hk/categories/services-1306/?addRecent=true&search=php',
  'https://www.carousell.com.hk/categories/services-1306/?addRecent=true&search=開發',
  'https://www.carousell.com.hk/categories/services-1306/?addRecent=true&search=wordpress',
  'https://www.carousell.com.hk/categories/services-1306/?addRecent=true&search=vba',
  'https://www.carousell.com.hk/categories/services-1306/?addRecent=true&search=ai',
  'https://www.carousell.com.hk/categories/services-1306/?addRecent=true&search=gpt',
];

(async () => {
  for (let i = 0; i < urls.length; i++) {
    let url = urls[i];
    await fetch('http://localhost:3000/carousell_search_by_keyword', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        url,
        // url: 'https://ib.bri.co.id/ib-bri',
        wait_before_read_s: 10,
        replace_filter: ['\n', '^ +$', '^.*ago$', '^.*views$', '^.*Now playing$', '^\\d+:\\d+$', '^\\d+:\\d+:\\d+$'],
      }),
    })
      .then(res => res.json())
      .then(body => console.log(JSON.stringify(body)))
      .catch(err => console.log(err));
  }
})();
