name: jobsdb_change_detect_workdesk_1

services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    # hostname: changedetection
    volumes:
      - ./volumes/changedetect/datastore:/datastore
    ports:
      - 5033:5000
    restart: unless-stopped
    environment:
      # - PLAYWRIGHT_DRIVER_URL=ws://sockpuppetbrowser:3000
      # - WEBDRIVER_URL=http://browser-chrome:4444/wd/hub
      - PLAYWRIGHT_DRIVER_URL=ws://browser-sockpuppet-chrome:3000
      - FETCH_WORKERS=1
      - PORT=5000
      - PUID=1000
      - PGID=1000
      # Maximum height of screenshots, default is 16000 px, screenshots will be clipped to this if exceeded.
      # RAM usage will be higher if you increase this.
      - SCREENSHOT_MAX_HEIGHT=16000
      - HIDE_REFERER=true
        # A valid timezone name to run as (for scheduling watch checking) see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=Asia/Hong_Kong

    depends_on:
      browser-sockpuppet-chrome:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '0.5'
        reservations:
          cpus: '0.01'

  browser-sockpuppet-chrome:
    hostname: browser-sockpuppet-chrome
    image: dgtlmoon/sockpuppetbrowser:latest
    cap_add:
      - SYS_ADMIN
    # SYS_ADMIN might be too much, but it can be needed on your platform https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-on-gitlabci
    restart: unless-stopped
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - MAX_CONCURRENT_CHROME_PROCESSES=2
    deploy:
      resources:
        limits:
          cpus: '0.5'
        reservations:
          cpus: '0.01'

  # db_data analysis, reporting
  docker_reporting:
    build:
      context: ./docker_reporting
    # container_name: chromium
    security_opt:
      - seccomp:unconfined #optional
    env_file:
      - ./.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Hong_Kong
      - CHROME_CLI=https://www.gmail.com/ #optional
      - CUSTOM_PORT=23000 # Internal port the container listens on for http if it needs to be swapped from the default 3000.
      - CUSTOM_HTTPS_PORT=23001 # Internal port the container listens on for https if it needs to be swapped from the default 3001.
      - NO_FULL=1 # Do not autmatically fullscreen applications when using openbox.
      - INSTALL_PACKAGES=fonts-noto-cjk
      #
      # python
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./volumes/docker_reporting/config:/config
      - ./volumes/docker_reporting/share:/share
      - ./src_reporting:/app_reporting
    ports:
      - 6085:23000 # http vnc port
      - 6086:3000 # service port
      - 23106:23001 # https vnc port
    shm_size: '1gb'
    restart: unless-stopped
    links:
      - pocketbase:pocketbase
    deploy:
      resources:
        limits:
          cpus: '1'
        reservations:
          cpus: '0.01'

  # work-horse, fetch list, fetch job details, draft email
  docker_chromium:
    # image: lscr.io/linuxserver/chromium:latest
    build:
      context: ./docker-chromium
    # container_name: chromium
    security_opt:
      - seccomp:unconfined #optional
    env_file:
      - ./.env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Hong_Kong
      - CHROME_CLI=https://www.gmail.com/ #optional
      - CUSTOM_PORT=23000 # Internal port the container listens on for http if it needs to be swapped from the default 3000.
      - CUSTOM_HTTPS_PORT=23001 # Internal port the container listens on for https if it needs to be swapped from the default 3001.
      - NO_FULL=1 # Do not autmatically fullscreen applications when using openbox.
      - INSTALL_PACKAGES=fonts-noto-cjk
      #
      # python
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./volumes/chromium/config:/config
      - ./volumes/chromium/share:/share
      - ./src:/app
      - ./src_py:/app_py
    ports:
      - 6084:3000 # service port
      - 6083:23000 # http vnc port
      - 23104:23001 # https vnc port
    shm_size: '1gb'
    restart: unless-stopped
    links:
      - pocketbase:pocketbase
    deploy:
      resources:
        limits:
          cpus: '1'
        reservations:
          cpus: '0.01'

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    # container_name: pocketbase
    # hostname: pocketbase
    restart: unless-stopped
    # environment:
    #   ENCRYPTION: example #optional
    ports:
      - 8197:8090
    volumes:
      # group custom persistant data inside docker directory
      - ./volumes/pocketbase/pb_data:/pb_data
      #
      # group dev, seed, schemas into pocketbase dirctory
      - ../pocketbase/pb_migrations:/pb_migrations
      - ../pocketbase/pb_hooks:/pb_hooks
    healthcheck:
      #optional (recommended) since v0.10.0
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

    deploy:
      resources:
        limits:
          cpus: '1'
        reservations:
          cpus: '0.01'
